version: '3.8'

services:
  # Backend FastAPI Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bionabu-backend
    ports:
      - "8000:8000"
    environment:
      - API_HOST=${API_HOST:-0.0.0.0}
      - API_PORT=${API_PORT:-8000}
      - API_V1_STR=${API_V1_STR:-/api/v1}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000,http://localhost:3001,http://127.0.0.1:3000}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - RATE_LIMIT_PER_MINUTE=${RATE_LIMIT_PER_MINUTE:-60}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-3.5-turbo}
      - OPENAI_MAX_TOKENS=${OPENAI_MAX_TOKENS:-4000}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE:-0.1}
    volumes:
      - ./ai/data:/app/data
      - ./ai/output:/app/output
      - ./ai/cache:/app/cache
      - ./backend:/app
    networks:
      - bionabu-network
    depends_on:
      - ai-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # AI Processing Service
  ai-service:
    build:
      context: ./ai
      dockerfile: Dockerfile
    container_name: bionabu-ai
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-3.5-turbo}
      - OPENAI_MAX_TOKENS=${OPENAI_MAX_TOKENS:-4000}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE:-0.1}
      - MAX_CONCURRENT_REQUESTS=${MAX_CONCURRENT_REQUESTS:-5}
      - REQUEST_DELAY=${REQUEST_DELAY:-1.0}
      - CHUNK_SIZE=${CHUNK_SIZE:-1000}
      - DATA_DIR=/app/data
      - OUTPUT_DIR=/app/output
      - CACHE_DIR=/app/cache
    volumes:
      - ./ai/data:/app/data
      - ./ai/output:/app/output
      - ./ai/cache:/app/cache
      - ./ai:/app
    networks:
      - bionabu-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend React Service (Commented out - not dockerizing yet)
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: bionabu-frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - REACT_APP_API_BASE_URL=http://localhost:8000
  #     - REACT_APP_API_VERSION=v1
  #     - REACT_APP_ENVIRONMENT=development
  #     - REACT_APP_DEBUG=true
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   networks:
  #     - bionabu-network
  #   depends_on:
  #     - backend
  #   restart: unless-stopped

networks:
  bionabu-network:
    driver: bridge
    name: bionabu-network

volumes:
  ai-data:
    driver: local
  ai-output:
    driver: local
  ai-cache:
    driver: local
